package com.sysdrill.backend.community

import com.sysdrill.backend.auth.AuthenticatedUserId
import com.sysdrill.backend.common.web.BadRequestException
import com.sysdrill.backend.common.web.ConflictException
import com.sysdrill.backend.identity.UserRepository
import com.sysdrill.backend.learning.DiagnosticPuzzleService
import com.sysdrill.backend.learning.DiagnosticPuzzleView
import com.sysdrill.backend.learning.DiagnosticPuzzles
import com.sysdrill.backend.learning.PuzzleAnswer
import com.sysdrill.backend.learning.PuzzleResult
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import jakarta.validation.Valid
import jakarta.validation.constraints.Size
import org.hibernate.annotations.CreationTimestamp
import org.springframework.dao.DataIntegrityViolationException
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Service
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RestController
import java.time.Instant
import java.time.ZoneId
import java.time.temporal.IsoFields
import java.util.UUID

@Entity
@Table(name = "wwyd_answers")
class WwydAnswer(
    @Id @GeneratedValue(strategy = GenerationType.UUID) var id: UUID? = null,
    @Column(nullable = false) var week: Int,
    @Column(name = "user_id", nullable = false) var userId: UUID,
    @Column(nullable = false) var choice: String,
    var reason: String? = null,
    @Column(name = "reason_public", nullable = false) var reasonPublic: Boolean = false,
    @CreationTimestamp @Column(name = "created_at", nullable = false, updatable = false) var createdAt: Instant? = null,
)

interface WwydAnswerRepository : JpaRepository<WwydAnswer, UUID> {
    fun findByWeekAndUserId(week: Int, userId: UUID): WwydAnswer?
    fun findByWeek(week: Int): List<WwydAnswer>
}

data class WwydSubmit(val choice: String, @field:Size(max = 200) val reason: String? = null, val reasonPublic: Boolean = false)

data class WwydReason(val nickname: String, val choice: String, val reason: String)

data class WeeklyPuzzleView(
    val week: Int,
    val puzzle: DiagnosticPuzzleView,
    /** Null until I answer — the distribution, the answer and others' reasons come only after. */
    val myChoice: String?,
    val distribution: Map<String, Int>?,
    val total: Int?,
    val result: PuzzleResult?,
    val reasons: List<WwydReason>?,
)

/**
 * docs/COMMUNITY_EXPANSION_PLAN.md C12 (PLAN.md Round E28) — one puzzle a week, seeded by the ISO
 * week so everyone sees the same one, generated by L9's generator (nothing authored, nothing stored
 * but the answers). Answer once; then the crowd's split and the public reasons appear.
 */
@Service
class WeeklyPuzzleService(
    private val repository: WwydAnswerRepository,
    private val puzzleService: DiagnosticPuzzleService,
    private val userRepository: UserRepository,
) {
    fun current(userId: UUID, now: Instant = Instant.now()): WeeklyPuzzleView {
        val week = weekOf(now)
        val set = DiagnosticPuzzles.setForWeek(week)
        val puzzle = puzzleService.puzzle(week.toLong(), set)
        val mine = repository.findByWeekAndUserId(week, userId)
            ?: return WeeklyPuzzleView(week, puzzle, null, null, null, null, null)
        val answers = repository.findByWeek(week)
        val publicReasons = answers.filter { it.reasonPublic && !it.reason.isNullOrBlank() }.sortedByDescending { it.createdAt }.take(MAX_REASONS)
        val nicknames = userRepository.findAllById(publicReasons.map { it.userId }).associate { it.id to it.nickname }
        return WeeklyPuzzleView(
            week = week,
            puzzle = puzzle,
            myChoice = mine.choice,
            distribution = set.checks.associate { c -> c.key to answers.count { it.choice == c.key } },
            total = answers.size,
            result = puzzleService.grade(week.toLong(), PuzzleAnswer(check = mine.choice), set),
            reasons = publicReasons.map { WwydReason(nicknames[it.userId] ?: "(알 수 없음)", it.choice, it.reason!!) },
        )
    }

    fun answer(userId: UUID, submit: WwydSubmit, now: Instant = Instant.now()): WeeklyPuzzleView {
        val week = weekOf(now)
        if (DiagnosticPuzzles.setForWeek(week).checks.none { it.key == submit.choice }) throw BadRequestException("알 수 없는 선택지: ${submit.choice}")
        if (repository.findByWeekAndUserId(week, userId) != null) throw ConflictException("이번 주 퍼즐에는 이미 답했습니다")
        try {
            repository.save(WwydAnswer(week = week, userId = userId, choice = submit.choice, reason = submit.reason?.trim()?.ifBlank { null }, reasonPublic = submit.reasonPublic))
        } catch (_: DataIntegrityViolationException) {
            throw ConflictException("이번 주 퍼즐에는 이미 답했습니다") // a double click racing the check above
        }
        return current(userId, now)
    }

    companion object {
        private const val MAX_REASONS = 10

        /** ISO year × 100 + ISO week, in Korean time (the product's users). */
        fun weekOf(now: Instant): Int {
            val date = now.atZone(ZoneId.of("Asia/Seoul")).toLocalDate()
            return date.get(IsoFields.WEEK_BASED_YEAR) * 100 + date.get(IsoFields.WEEK_OF_WEEK_BASED_YEAR)
        }
    }
}

@RestController
class WeeklyPuzzleController(private val service: WeeklyPuzzleService) {
    @GetMapping("/community/wwyd")
    fun current(@AuthenticatedUserId userId: UUID): WeeklyPuzzleView = service.current(userId)

    @PostMapping("/community/wwyd")
    fun answer(@AuthenticatedUserId userId: UUID, @Valid @RequestBody submit: WwydSubmit): WeeklyPuzzleView = service.answer(userId, submit)
}
