-- docs/LEARNING_COMMUNITY_PLAN.md §5.2 / ADR-0039 — 개념 25개 시드.
--
-- 내용의 출처는 두 곳이다: 기존 frontend/src/lib/riskLabels.ts 의 라벨·설명(이
-- 마이그레이션 이후 프론트에서 제거된다)과, RuleEvaluator 가 실제로 채점하는
-- 기준. 개념 설명이 채점 기준과 같은 어휘를 쓰는 것이 이 기능의 핵심이라,
-- 새 용어를 만들지 않고 riskKey 와 카테고리를 그대로 따른다.
--
-- category 값은 RuleEvaluator.categoryByRiskKey 와 반드시 일치해야 한다 —
-- LearningConceptCatalogTest 가 두 목록이 어긋나면 실패한다.

insert into learning_concepts (
    risk_key, category, label, summary, why_it_matters,
    symptoms, patterns, tradeoffs, related_domains, related_actions, related_challenges, display_order
) values
    ($ct$MISSING_IDEMPOTENCY$ct$, $ct$CONCURRENCY_CONSISTENCY$ct$, $ct$멱등성 처리$ct$,
     $ct$같은 요청이 두 번 도착해도 결과가 한 번 처리한 것과 같아야 한다.$ct$,
     $ct$클라이언트 재시도, 큐의 at-least-once 재배달, 사용자의 더블클릭은 버그가 아니라 정상 동작이다. 방어가 없으면 쿠폰 중복 발급·이중 결제처럼 되돌리기 어려운 결과가 남는다.$ct$,
     $ct$["발급 수가 재고보다 많아짐", "DB 유니크 제약 위반 급증", "주문 건수와 결제 건수 불일치"]$ct$::jsonb, $ct$["요청에 멱등키를 실어 저장소에 기록하고 재요청이면 저장된 결과를 반환", "DB 유니크 제약으로 두 번째 INSERT를 실패시키기", "조건부 UPDATE(현재 상태를 WHERE 에 포함)"]$ct$::jsonb,
     $ct$멱등키 저장소가 추가 의존성이 된다. TTL 이 짧으면 늦게 온 재시도를 못 막고, 길면 메모리를 계속 먹는다.$ct$,
     $ct$["coupon", "payment"]$ct$::jsonb, $ct$["ENABLE_IDEMPOTENT_PG_RETRY"]$ct$::jsonb, $ct$["rate-limiter"]$ct$::jsonb, 1),
    ($ct$MISSING_CONCURRENCY_CONTROL$ct$, $ct$CONCURRENCY_CONSISTENCY$ct$, $ct$동시성 제어$ct$,
     $ct$여러 요청이 같은 자원을 동시에 건드릴 때 경쟁 상태로 데이터가 깨지지 않게 한다.$ct$,
     $ct$읽고-판단하고-쓰는 사이에 다른 요청이 끼어들면 재고가 음수가 되거나 좌석이 두 번 팔린다. 부하가 낮을 때는 거의 드러나지 않다가 트래픽이 몰리는 순간 터진다.$ct$,
     $ct$["재고가 음수", "같은 자원에 확정이 2건", "락 대기 시간 급증, DB pool 사용률 포화"]$ct$::jsonb, $ct$["원자적 연산 하나로 합치기(Redis Lua, DB 의 조건부 UPDATE)", "비관적 락 — 정확하지만 처리량을 깎는다", "낙관적 락(버전 컬럼) + 충돌 시 재시도"]$ct$::jsonb,
     $ct$락 범위를 넓게 잡으면 안전하지만 동시 처리량이 곧바로 떨어진다. 좁게 잡으면 빠르지만 빠뜨린 경로에서 깨진다.$ct$,
     $ct$["coupon", "reservation"]$ct$::jsonb, $ct$["ENABLE_FINE_GRAINED_LOCKING"]$ct$::jsonb, $ct$["distributed-lock"]$ct$::jsonb, 2),
    ($ct$MISSING_IDEMPOTENT_CONSUMER$ct$, $ct$CONCURRENCY_CONSISTENCY$ct$, $ct$Idempotent Consumer$ct$,
     $ct$큐 컨슈머가 같은 메시지를 두 번 받아도 한 번만 처리한 효과를 내야 한다.$ct$,
     $ct$대부분의 큐는 at-least-once 다 — 중복 배달은 예외가 아니라 정상이다. 컨슈머가 이를 전제하지 않으면 알림이 두 번 가고 정산이 두 번 반영된다.$ct$,
     $ct$["동일 사용자에게 알림 중복 발송", "처리 건수가 발행 건수보다 많음", "재처리 후 합계가 어긋남"]$ct$::jsonb, $ct$["메시지 ID 를 처리 기록 테이블에 유니크 제약으로 남기기", "처리 결과를 upsert 로 만들어 재실행해도 같은 상태가 되게 하기", "비즈니스 키 기준 중복 검사"]$ct$::jsonb,
     $ct$처리 기록을 영원히 보관할 수 없으므로 보존 기간을 정해야 하고, 그 기간을 넘겨 도착한 중복은 막지 못한다.$ct$,
     $ct$["notification", "batch-settlement"]$ct$::jsonb, $ct$[]$ct$::jsonb, $ct$["queue", "event-bus"]$ct$::jsonb, 3),
    ($ct$MISSING_PAYMENT_IDEMPOTENCY$ct$, $ct$CONCURRENCY_CONSISTENCY$ct$, $ct$결제 멱등성$ct$,
     $ct$결제 재시도가 이중 결제로 이어지지 않게 한다.$ct$,
     $ct$결제는 되돌리는 비용이 가장 비싼 작업이다. 응답을 못 받은 클라이언트는 반드시 재시도하는데, 그 재시도가 새 결제로 잡히면 환불·CS 비용이 즉시 발생한다.$ct$,
     $ct$["동일 주문에 승인 건이 2건", "PG 대사(對査) 결과 불일치", "환불 요청 급증"]$ct$::jsonb, $ct$["주문 단위 멱등키를 PG 요청에 그대로 전달", "승인 전 기존 승인 조회", "주문 상태를 조건부 UPDATE 로 전이"]$ct$::jsonb,
     $ct$PG 사마다 멱등키 지원 범위와 보존 기간이 달라, 우리 쪽에도 별도 기록이 필요하다.$ct$,
     $ct$["payment"]$ct$::jsonb, $ct$["ENABLE_IDEMPOTENT_PG_RETRY"]$ct$::jsonb, $ct$[]$ct$::jsonb, 4),
    ($ct$MISSING_TRANSACTION_BOUNDARY$ct$, $ct$CONCURRENCY_CONSISTENCY$ct$, $ct$트랜잭션 경계 분리$ct$,
     $ct$DB 트랜잭션과 외부 API 호출처럼 한 트랜잭션으로 묶을 수 없는 작업을 어떻게 일관되게 만들지 정한다.$ct$,
     $ct$외부 호출을 트랜잭션 안에 두면 커넥션을 붙든 채 네트워크를 기다리게 되고, 밖에 두면 둘 중 하나만 성공하는 창이 생긴다. 어느 쪽이든 선택과 보정책이 필요하다.$ct$,
     $ct$["DB 커넥션 풀 고갈(외부 응답 대기 중 점유)", "결제는 됐는데 주문이 없음(또는 반대)", "커밋 직후 후속 처리 유실"]$ct$::jsonb, $ct$["Outbox — 같은 트랜잭션에 이벤트를 저장하고 커밋 후 발행", "Saga + 보상 트랜잭션", "커밋 이후 훅에서만 외부 호출(이 저장소의 ADR-0004 와 같은 원리)"]$ct$::jsonb,
     $ct$Outbox 는 발행 지연과 테이블 하나를 더 요구하고, Saga 는 보상 로직을 모두 직접 써야 한다.$ct$,
     $ct$["payment"]$ct$::jsonb, $ct$["ISOLATE_PAYMENT_POOL"]$ct$::jsonb, $ct$[]$ct$::jsonb, 5),
    ($ct$MISSING_RESERVATION_LOCKING$ct$, $ct$CONCURRENCY_CONSISTENCY$ct$, $ct$예약 락$ct$,
     $ct$동시 예약에서 좌석·슬롯 잠금을 어느 단위로 걸지 정한다.$ct$,
     $ct$락의 세분화 수준이 곧 유효 처리 용량이다. 공연 전체에 락을 걸면 한 번에 한 명만 예약할 수 있고, 좌석마다 걸면 동시에 수백 명을 받을 수 있다.$ct$,
     $ct$["예약 처리량이 좌석 수와 무관하게 일정", "락 대기로 p95 급등", "타임아웃 후 재시도 폭주"]$ct$::jsonb, $ct$["자원 단위(좌석 ID) 락", "구역 단위로 나눠 경합 분산", "원자적 조건부 UPDATE 로 락 자체를 없애기"]$ct$::jsonb,
     $ct$락을 잘게 쪼갤수록 동시성은 올라가지만 교착(deadlock) 가능성과 관리 복잡도가 함께 올라간다.$ct$,
     $ct$["reservation"]$ct$::jsonb, $ct$["ENABLE_FINE_GRAINED_LOCKING"]$ct$::jsonb, $ct$["distributed-lock"]$ct$::jsonb, 6),
    ($ct$MISSING_INVENTORY_CONSISTENCY$ct$, $ct$CONCURRENCY_CONSISTENCY$ct$, $ct$재고 정합성$ct$,
     $ct$잔여 수량 확인과 확정을 원자적으로 처리해 초과 판매를 막는다.$ct$,
     $ct$"조회 후 확정"을 두 단계로 나누면 그 사이에 다른 요청이 같은 수량을 보게 된다. 초과 판매는 사용자에게 사과하고 취소해야 하는, 가장 비싼 종류의 버그다.$ct$,
     $ct$["확정 수가 총 재고를 초과", "취소·사과 CS 증가", "재고 카운터와 확정 레코드 수 불일치"]$ct$::jsonb, $ct$["감소와 확인을 한 연산으로(DECR 후 음수면 롤백)", "조건부 UPDATE(quantity > 0 을 WHERE 에)", "확정 레코드에 유니크 제약을 둬 최종 방어선 만들기"]$ct$::jsonb,
     $ct$원자 연산을 쓰려면 재고를 한 곳에 모아야 해서 그 지점이 hot key 가 된다.$ct$,
     $ct$["reservation", "coupon"]$ct$::jsonb, $ct$["ENABLE_ATOMIC_INVENTORY_CHECK"]$ct$::jsonb, $ct$[]$ct$::jsonb, 7),
    ($ct$MISSING_RECONCILIATION$ct$, $ct$CONCURRENCY_CONSISTENCY$ct$, $ct$정산 정합성$ct$,
     $ct$재처리 시 이미 반영된 레코드가 중복 집계되지 않게 한다.$ct$,
     $ct$배치는 실패하면 다시 돌린다. 재처리가 안전하지 않으면 한 번의 장애가 잘못된 정산 금액으로 이어지고, 그 오류는 보통 한참 뒤에 발견된다.$ct$,
     $ct$["재처리 후 정산 합계 증가", "같은 거래가 두 번 집계", "원장과 대사 결과 불일치"]$ct$::jsonb, $ct$["처리 완료 마킹 후 다음 실행에서 제외", "집계를 덮어쓰기(upsert)로 만들어 재실행에 안전하게", "기간 단위로 삭제 후 재삽입"]$ct$::jsonb,
     $ct$처리 완료 마킹은 추가 쓰기를 발생시키고, 덮어쓰기는 중간 상태를 남기지 않아 추적이 어려워진다.$ct$,
     $ct$["batch-settlement"]$ct$::jsonb, $ct$["ENABLE_IDEMPOTENT_RECONCILIATION"]$ct$::jsonb, $ct$[]$ct$::jsonb, 8),
    ($ct$MISSING_RATE_LIMIT$ct$, $ct$RESILIENCE$ct$, $ct$Rate Limit$ct$,
     $ct$단위 시간당 허용 요청 수를 제한해 뒷단을 보호한다.$ct$,
     $ct$보호 장치가 없으면 트래픽 급증이 그대로 DB 까지 전달돼 전체가 무너진다. 일부 요청을 거절하는 것이 전원이 실패하는 것보다 낫다.$ct$,
     $ct$["DB 커넥션 풀 사용률 포화", "p95 지연 급등 후 에러율 상승", "특정 사용자·IP 가 트래픽의 대부분 차지"]$ct$::jsonb, $ct$["Token Bucket — 순간 버스트 허용", "Sliding Window — 경계 구간 왜곡이 적음", "사용자·IP·엔드포인트 등 다층 적용"]$ct$::jsonb,
     $ct$정상 사용자도 거절될 수 있어 UX 가 나빠진다. 분산 환경에서 정확히 세려면 공유 저장소가 필요하고, 그 저장소가 새 장애 지점이 된다.$ct$,
     $ct$["coupon"]$ct$::jsonb, $ct$["STRENGTHEN_RATE_LIMIT"]$ct$::jsonb, $ct$["rate-limiter", "rate-limiter-ts"]$ct$::jsonb, 1),
    ($ct$MISSING_RETRY_BACKOFF$ct$, $ct$RESILIENCE$ct$, $ct$Retry/Backoff$ct$,
     $ct$실패를 즉시 재시도하지 않고 대기 시간을 늘려가며 재시도한다.$ct$,
     $ct$장애 중인 대상에 즉시 재시도가 몰리면 재시도 폭풍이 되어 복구를 방해한다. 회복하려는 시스템에 가장 큰 부하를 주는 것이 보통 재시도다.$ct$,
     $ct$["장애 발생 직후 요청 수가 오히려 증가", "복구 후에도 부하가 안 떨어짐", "동일 요청이 로그에 반복"]$ct$::jsonb, $ct$["지수 백오프 + 지터(동시 재시도 시점 분산)", "재시도 총 횟수·총 시간 상한", "재시도해도 소용없는 오류(4xx)는 즉시 포기"]$ct$::jsonb,
     $ct$백오프를 길게 잡으면 일시적 장애에서의 회복이 느려진다. 지터가 없으면 재시도가 같은 순간에 다시 몰린다.$ct$,
     $ct$["notification", "payment"]$ct$::jsonb, $ct$["ADJUST_RETRY_BACKOFF", "ENABLE_IDEMPOTENT_PG_RETRY"]$ct$::jsonb, $ct$["retry-backoff"]$ct$::jsonb, 2),
    ($ct$MISSING_DLQ$ct$, $ct$RESILIENCE$ct$, $ct$DLQ (Dead Letter Queue)$ct$,
     $ct$반복 실패하는 메시지를 격리해 파이프라인 전체가 막히지 않게 한다.$ct$,
     $ct$처리 불가능한 메시지 하나가 큐 맨 앞에 있으면 뒤의 정상 메시지가 전부 멈춘다(head-of-line blocking). 한 건의 문제가 전체 지연으로 번진다.$ct$,
     $ct$["consumer lag 이 계속 증가", "같은 메시지 오류 로그 반복", "처리량이 0 에 수렴"]$ct$::jsonb, $ct$["N 회 실패 후 별도 큐로 이동", "DLQ 적재량을 알람 대상으로", "원인 수정 후 재투입 경로 마련"]$ct$::jsonb,
     $ct$DLQ 는 자동 복구가 아니라 사람이 봐야 하는 대기열이다. 알람과 운영 절차가 없으면 조용히 쌓이기만 한다.$ct$,
     $ct$["notification"]$ct$::jsonb, $ct$[]$ct$::jsonb, $ct$["queue", "event-bus"]$ct$::jsonb, 3),
    ($ct$MISSING_CIRCUIT_BREAKER$ct$, $ct$RESILIENCE$ct$, $ct$Circuit Breaker$ct$,
     $ct$계속 실패하는 의존성 호출을 일정 시간 차단해 빠르게 실패한다.$ct$,
     $ct$느린 외부 의존성을 계속 기다리면 스레드와 커넥션이 묶여 장애가 우리 시스템 전체로 번진다. 차단은 포기가 아니라 격리다.$ct$,
     $ct$["외부 의존성 지연 상승과 동시에 우리 p95 상승", "스레드 풀·커넥션 풀 고갈", "타임아웃 오류가 전체 에러의 대부분"]$ct$::jsonb, $ct$["실패율 임계치 초과 시 open", "일정 시간 후 half-open 으로 소량만 통과시켜 탐색", "열린 동안 대체 응답(degradation) 제공"]$ct$::jsonb,
     $ct$임계치가 민감하면 멀쩡한 의존성을 끊고, 둔하면 차단이 늦어 이미 번진 뒤가 된다.$ct$,
     $ct$["notification", "payment"]$ct$::jsonb, $ct$["ENABLE_CIRCUIT_BREAKER"]$ct$::jsonb, $ct$["circuit-breaker"]$ct$::jsonb, 4),
    ($ct$MISSING_PG_RETRY_BACKOFF$ct$, $ct$RESILIENCE$ct$, $ct$PG 재시도/백오프$ct$,
     $ct$결제대행사 장애나 응답 유실 시의 재시도 전략을 정한다.$ct$,
     $ct$결제는 부분 실패가 가장 위험한 영역이다 — 승인은 됐는데 응답만 유실된 경우, 단순 재시도는 곧바로 이중 결제가 된다.$ct$,
     $ct$["PG 응답 지연 상승", "승인 상태 불명 건 증가", "대사 불일치"]$ct$::jsonb, $ct$["멱등키를 동반한 재시도만 허용", "재시도 전 승인 조회로 상태 확인", "일정 횟수 후 보류 처리하고 사람이 확인"]$ct$::jsonb,
     $ct$조회 API 자체도 장애 중일 수 있어, 결국 일부는 사람이 처리하는 보류 큐가 필요하다.$ct$,
     $ct$["payment"]$ct$::jsonb, $ct$["ENABLE_IDEMPOTENT_PG_RETRY"]$ct$::jsonb, $ct$["retry-backoff"]$ct$::jsonb, 5),
    ($ct$MISSING_ROLLOUT_SAFETY$ct$, $ct$RESILIENCE$ct$, $ct$무중단 배포$ct$,
     $ct$배포 도중 가용 용량이 줄지 않도록 장치를 둔다.$ct$,
     $ct$트래픽이 높은 시간대의 롤링 업데이트는 그 자체가 장애 유발 요인이다. 준비되지 않은 Pod 에 트래픽이 가거나, 동시에 너무 많이 내려가면 남은 Pod 가 무너진다.$ct$,
     $ct$["배포 시작 직후 에러율 급등", "Pod 재시작 반복", "가용 Pod 수가 최소 기준 아래로"]$ct$::jsonb, $ct$["readiness probe 로 준비된 Pod 에만 트래픽 전달", "PodDisruptionBudget 으로 동시 중단 수 제한", "카나리·단계적 롤아웃"]$ct$::jsonb,
     $ct$안전장치를 촘촘히 걸수록 배포가 느려지고, 롤백까지의 시간도 함께 길어진다.$ct$,
     $ct$["autoscaling"]$ct$::jsonb, $ct$["ENABLE_ROLLOUT_SAFEGUARD"]$ct$::jsonb, $ct$[]$ct$::jsonb, 6),
    ($ct$MISSING_CACHE_POLICY_SEPARATION$ct$, $ct$CACHING_DATA_ACCESS$ct$, $ct$캐시 정책 분리$ct$,
     $ct$변경 빈도가 다른 데이터에 서로 다른 TTL·캐시 전략을 적용한다.$ct$,
     $ct$가격처럼 항상 최신이어야 하는 데이터와 리뷰처럼 조금 낡아도 되는 데이터에 같은 TTL 을 쓰면, 한쪽 기준에 맞추는 순간 다른 쪽이 손해를 본다. 짧게 맞추면 hit ratio 가 떨어지고, 길게 맞추면 잘못된 가격을 보여준다.$ct$,
     $ct$["cache hit ratio 가 기대보다 낮음", "TTL 을 늘리면 stale 불만, 줄이면 DB 부하 증가", "특정 화면만 유독 느림"]$ct$::jsonb, $ct$["데이터 종류별 TTL 분리", "최신성이 필수인 항목은 캐시 제외 또는 쓰기 시 무효화", "stale-while-revalidate 로 응답은 즉시, 갱신은 뒤에서"]$ct$::jsonb,
     $ct$정책이 늘어날수록 무효화 경로가 복잡해지고, 어느 데이터가 언제 낡는지 추적하기 어려워진다.$ct$,
     $ct$["product-browsing"]$ct$::jsonb, $ct$["SPLIT_CACHE_POLICY", "INCREASE_CACHE_TTL"]$ct$::jsonb, $ct$[]$ct$::jsonb, 1),
    ($ct$MISSING_KEY_DISTRIBUTION$ct$, $ct$CACHING_DATA_ACCESS$ct$, $ct$Hot Key 분산$ct$,
     $ct$한 키에 트래픽이 몰려 특정 노드만 과부하되는 현상을 막는다.$ct$,
     $ct$전체 평균 부하는 여유로운데 한 샤드만 100% 인 상황은 흔하다. 이벤트 상품 하나, 인기 게시물 하나가 전체 캐시 계층의 병목이 된다.$ct$,
     $ct$["노드별 CPU 편차가 큼", "전체 처리량은 낮은데 특정 키 지연만 높음", "캐시 노드 하나만 응답 지연"]$ct$::jsonb, $ct$["키에 샤드 접미사를 붙여 N 개로 분산", "인기 키를 로컬(인프로세스) 캐시로 한 겹 더", "읽기 전용 복제본 추가"]$ct$::jsonb,
     $ct$샤딩하면 총합이 필요한 연산(정확한 잔여 재고 등)이 어려워진다. 로컬 캐시는 인스턴스 간 불일치를 만든다.$ct$,
     $ct$["product-browsing", "coupon"]$ct$::jsonb, $ct$[]$ct$::jsonb, $ct$[]$ct$::jsonb, 2),
    ($ct$MISSING_SINGLE_FLIGHT$ct$, $ct$CACHING_DATA_ACCESS$ct$, $ct$Single-flight$ct$,
     $ct$같은 키에 대한 동시 조회를 하나로 합쳐 뒷단에 한 번만 간다.$ct$,
     $ct$인기 키의 캐시가 만료되는 순간 대기 중이던 요청이 한꺼번에 DB 로 쏟아진다(cache stampede). 평소엔 안 보이다가 TTL 만료 주기마다 규칙적으로 터진다.$ct$,
     $ct$["TTL 주기와 같은 간격으로 DB 부하 스파이크", "cache miss 직후 p95 급등", "동일 쿼리가 짧은 시간에 수백 건"]$ct$::jsonb, $ct$["진행 중인 조회에 후속 요청을 합류시키고 결과 공유", "만료 전에 미리 갱신(refresh-ahead)", "TTL 에 지터를 줘 만료 시점 분산"]$ct$::jsonb,
     $ct$합류 대기 중 조회가 실패하면 기다리던 요청이 전부 함께 실패한다. 구현이 잘못되면 그 자체가 병목이 된다.$ct$,
     $ct$["product-browsing"]$ct$::jsonb, $ct$["ENABLE_SINGLE_FLIGHT"]$ct$::jsonb, $ct$[]$ct$::jsonb, 3),
    ($ct$MISSING_READ_REPLICA$ct$, $ct$CACHING_DATA_ACCESS$ct$, $ct$Read Replica$ct$,
     $ct$읽기 전용 복제본으로 읽기 트래픽을 분산한다.$ct$,
     $ct$읽기가 쓰기보다 훨씬 많은 서비스에서 하나의 DB 가 둘 다 받으면 읽기가 쓰기 성능까지 끌어내린다. 복제본은 가장 손쉬운 수평 확장 수단이다.$ct$,
     $ct$["DB 읽기 부하가 쓰기보다 압도적", "주 DB CPU 포화", "읽기 쿼리 대기 증가"]$ct$::jsonb, $ct$["조회 트래픽을 복제본으로 라우팅", "쓰기 직후 읽기는 주 DB 로(read-your-writes)", "복제 지연을 지표로 감시"]$ct$::jsonb,
     $ct$복제 지연 때문에 방금 쓴 데이터가 안 보일 수 있다. 어떤 화면이 최신성을 요구하는지 미리 정해야 한다.$ct$,
     $ct$["product-browsing"]$ct$::jsonb, $ct$["ADD_READ_REPLICA"]$ct$::jsonb, $ct$[]$ct$::jsonb, 4),
    ($ct$MISSING_ASYNC_BOUNDARY$ct$, $ct$ASYNC_BATCH$ct$, $ct$비동기 경계$ct$,
     $ct$즉시 처리할 것과 나중에 처리할 것을 명확히 나눈다.$ct$,
     $ct$사용자 응답에 꼭 필요하지 않은 작업(알림 발송, 집계, 외부 연동)을 동기로 처리하면 응답 시간이 가장 느린 의존성에 묶이고, 그 의존성의 장애가 그대로 사용자에게 전달된다.$ct$,
     $ct$["응답 시간이 외부 의존성 지연을 그대로 따라감", "부가 기능 장애가 핵심 기능까지 실패시킴", "요청 스레드 점유 시간이 김"]$ct$::jsonb, $ct$["핵심 경로만 동기, 나머지는 큐로", "커밋 후 이벤트 발행(이 저장소의 ADR-0004)", "사용자에게는 접수 완료, 처리 결과는 별도 조회"]$ct$::jsonb,
     $ct$비동기로 옮기면 결과가 즉시 보이지 않아 UX 설명이 필요하고, 실패를 사용자에게 알릴 경로를 따로 만들어야 한다.$ct$,
     $ct$["coupon", "notification"]$ct$::jsonb, $ct$[]$ct$::jsonb, $ct$["queue", "event-bus"]$ct$::jsonb, 1),
    ($ct$MISSING_CHUNKING$ct$, $ct$ASYNC_BATCH$ct$, $ct$청킹$ct$,
     $ct$대용량 배치를 작은 단위로 끊어 처리한다.$ct$,
     $ct$한 번에 전부 처리하면 메모리가 터지고, 실패 시 처음부터 다시 해야 하며, 그동안 트랜잭션이 자원을 계속 점유한다. 청크 크기가 곧 실패 시 손실 범위다.$ct$,
     $ct$["배치 실행 중 메모리 사용량 급증", "긴 트랜잭션으로 락 경합", "실패 시 전체 재실행"]$ct$::jsonb, $ct$["고정 크기 청크 단위 커밋", "청크마다 진행 상황 기록", "처리량과 재처리 비용을 보고 크기 조정"]$ct$::jsonb,
     $ct$청크가 작으면 커밋 오버헤드로 전체 처리량이 떨어지고, 크면 실패 시 되돌릴 양이 많아진다.$ct$,
     $ct$["batch-settlement"]$ct$::jsonb, $ct$["REDUCE_CHUNK_SIZE"]$ct$::jsonb, $ct$[]$ct$::jsonb, 2),
    ($ct$MISSING_RESTARTABILITY$ct$, $ct$ASYNC_BATCH$ct$, $ct$재시작 가능성$ct$,
     $ct$중간 실패 시 처음이 아니라 체크포인트부터 이어서 재개한다.$ct$,
     $ct$여섯 시간짜리 배치가 다섯 시간째에 실패했을 때 처음부터 다시 돌리면 그날 안에 못 끝낸다. 재시작 가능성은 성능 문제가 아니라 운영 가능성 문제다.$ct$,
     $ct$["재실행 시간이 원래 실행 시간과 같음", "야간 배치가 업무 시간까지 이어짐", "같은 구간을 반복 처리"]$ct$::jsonb, $ct$["처리 완료 지점을 저장하고 재개 시 그 이후부터", "이미 처리한 레코드를 건너뛰도록 마킹", "실패 구간만 재처리하는 경로 분리"]$ct$::jsonb,
     $ct$체크포인트 기록이 추가 쓰기 비용이고, 재개 지점이 정확하지 않으면 중복 처리나 누락이 생긴다.$ct$,
     $ct$["batch-settlement"]$ct$::jsonb, $ct$["ENABLE_CHECKPOINT_RESTART"]$ct$::jsonb, $ct$[]$ct$::jsonb, 3),
    ($ct$MISSING_RESERVATION_TIMEOUT$ct$, $ct$CAPACITY_TIMING$ct$, $ct$예약 타임아웃$ct$,
     $ct$결제를 마치지 않고 이탈한 홀드를 자동으로 해제한다.$ct$,
     $ct$홀드가 풀리지 않으면 실제로는 비어 있는 좌석이 계속 판매 불가로 남는다. 재고가 있는데도 못 파는 상태가 조용히 누적된다.$ct$,
     $ct$["가용 재고는 0 인데 확정 건수는 적음", "홀드 건수가 계속 증가", "전환율 대비 매출 저조"]$ct$::jsonb, $ct$["홀드에 만료 시각을 두고 주기적으로 회수", "만료 시각을 넘긴 홀드는 조회 시점에 무효 처리", "만료 전 사용자에게 알림"]$ct$::jsonb,
     $ct$타임아웃이 짧으면 결제 중인 사용자의 예약이 풀리고, 길면 재고가 오래 묶인다.$ct$,
     $ct$["reservation"]$ct$::jsonb, $ct$["SHORTEN_HOLD_TIMEOUT"]$ct$::jsonb, $ct$[]$ct$::jsonb, 1),
    ($ct$MISSING_AUTOSCALING$ct$, $ct$CAPACITY_TIMING$ct$, $ct$오토스케일링$ct$,
     $ct$트래픽 변화에 맞춰 인스턴스 수를 자동으로 조절한다.$ct$,
     $ct$고정 용량은 평시에 낭비이고 급증 시 부족하다. 다만 스케일 아웃에는 지연이 있어서, 급증이 시작된 뒤에 늘리기 시작하면 이미 늦는 경우가 많다.$ct$,
     $ct$["트래픽 급증 구간에서 CPU 포화 후 에러율 상승", "스케일 아웃 완료 시점이 피크 이후", "평시 사용률이 매우 낮음"]$ct$::jsonb, $ct$["CPU·요청 수 기준 HPA", "예측 가능한 이벤트는 사전 스케일 아웃", "스케일 인은 보수적으로(쿨다운)"]$ct$::jsonb,
     $ct$늘어난 인스턴스가 DB 커넥션을 더 요구해 병목이 DB 로 옮겨갈 수 있다. 스케일 아웃이 문제를 이동시키기만 하는 경우가 흔하다.$ct$,
     $ct$["autoscaling"]$ct$::jsonb, $ct$["SCALE_OUT_REPLICAS"]$ct$::jsonb, $ct$[]$ct$::jsonb, 2),
    ($ct$MISSING_RESOURCE_LIMITS$ct$, $ct$CAPACITY_TIMING$ct$, $ct$리소스 제한$ct$,
     $ct$컨테이너의 CPU·메모리 요청량과 상한을 설정한다.$ct$,
     $ct$상한이 없으면 한 인스턴스가 노드 전체 자원을 먹어 이웃까지 죽이고, 너무 낮으면 OOM 으로 재시작을 반복한다. 요청량이 없으면 스케줄러가 배치를 잘못한다.$ct$,
     $ct$["OOMKilled 로 인한 재시작 반복", "같은 노드의 무관한 서비스까지 지연", "스케줄링 실패 또는 편중"]$ct$::jsonb, $ct$["실측 사용량 기준으로 request 설정", "limit 은 급증을 흡수할 여유를 두되 노드를 보호할 만큼", "OOM·throttling 을 지표로 감시"]$ct$::jsonb,
     $ct$limit 을 넉넉히 주면 밀도가 떨어져 비용이 오르고, 빡빡하게 주면 스파이크에서 죽는다.$ct$,
     $ct$["autoscaling"]$ct$::jsonb, $ct$["TUNE_RESOURCE_LIMITS"]$ct$::jsonb, $ct$[]$ct$::jsonb, 3),
    ($ct$MISSING_OBSERVABILITY$ct$, $ct$OBSERVABILITY$ct$, $ct$관측 가능성$ct$,
     $ct$metrics·logs·traces 로 내부 상태를 밖에서 파악할 수 있게 한다.$ct$,
     $ct$장애 대응 시간의 대부분은 고치는 시간이 아니라 원인을 찾는 시간이다. 관측 수단이 없으면 MTTD 와 MTTR 이 함께 늘어나고, 가설을 세울 근거 자체가 없다.$ct$,
     $ct$["장애를 사용자 신고로 처음 알게 됨", "원인 후보를 좁히지 못하고 추측으로 조치", "조치 후 나아졌는지 확인 불가"]$ct$::jsonb, $ct$["핵심 지표(처리량·지연 p95/p99·에러율·포화도) 대시보드", "SLO 기반 알람 — 증상 중심으로", "요청 단위 분산 추적으로 구간별 지연 분해"]$ct$::jsonb,
     $ct$지표와 로그는 저장·전송 비용이고, 알람이 너무 많으면 아무도 보지 않게 된다.$ct$,
     $ct$["coupon", "notification", "product-browsing", "payment", "reservation", "batch-settlement", "autoscaling"]$ct$::jsonb, $ct$[]$ct$::jsonb, $ct$[]$ct$::jsonb, 1);
