-- docs/LEARNING_EXPANSION_PLAN.md L8 (PLAN.md Round E19) — 장애 패턴 사전 + 개념의 Bad Fixes / When NOT to use.
-- 장애 패턴은 인시던트 도메인과 1:1이라 도메인을 키로 둔다(개념 PK는 riskKey라 축이 다름).
-- 잘못된 대응(bad_fixes)은 새로 지어낸 것이 아니라 엔진이 이미 계산하는 액션 부작용(ARCHITECTURE §6.4)을 문장으로 옮긴 것이다.
create table failure_patterns (
    domain varchar(64) primary key,
    name varchar(200) not null,
    summary text not null,
    symptoms jsonb not null,
    typical_metrics jsonb not null,
    typical_logs jsonb not null,
    common_causes jsonb not null,
    bad_fixes jsonb not null,
    mitigations jsonb not null,
    prevention jsonb not null,
    related_concepts jsonb not null,
    display_order int not null
);

insert into failure_patterns values ('coupon', 'Hot Key · DB 쓰기 포화', '선착순 이벤트처럼 한순간 트래픽이 한 키와 한 테이블에 몰려, 캐시 계층이 느려지고 DB 쓰기와 커넥션 풀이 먼저 바닥나는 장애.', '["이벤트 시작 직후 P95와 에러율이 동시에 치솟는다", "Redis 응답 시간이 평소의 몇 배가 되고 캐시 적중률이 떨어진다", "DB 쓰기 부하가 100%를 넘고 커넥션 풀 대기가 생긴다"]', '["DB 쓰기 부하 ≥ 100%", "커넥션 풀 사용률 100%", "Redis 지연 증가 · 캐시 적중률 하락", "에러율(5xx) 급증"]', '["HikariPool-1 - Connection is not available, request timed out after 30000ms", "GET coupon:stock:{eventId} took 30ms", "POST /coupons/issue 503 upstream timeout"]', '["재고 차감이 한 행(또는 한 키)에 집중되는 설계", "유입량을 제한하지 않아 DB가 그대로 버스트를 받음", "캐시가 느려지자 읽기까지 DB로 쏟아짐"]', '[{"fix": "DB 커넥션 풀만 늘리기", "why": "대기 요청은 잠시 줄지만 DB 자체 쓰기 한계를 넘기면 풀이 커질수록 경합만 커진다. 캐시 쪽 증상(Redis 지연)은 그대로다."}, {"fix": "캐시 TTL만 길게 늘리기", "why": "읽기 부하는 덜어도 재고 차감(쓰기) 병목은 그대로이고, 남은 수량 같은 값이 오래된 채 보인다(stale)."}]', '["Rate Limit으로 DB가 감당할 만큼만 받아들이기", "캐시 TTL 조정으로 읽기를 DB에서 떼어내기", "풀 증설은 DB 한계를 확인한 뒤 마지막에"]', '["재고 차감을 Redis 원자 연산·큐로 분리해 DB는 확정만 기록", "유저별 멱등 키로 재시도 중복 차단", "이벤트 전 부하 테스트와 Rate Limit 기본값"]', '["MISSING_RATE_LIMIT", "MISSING_CONCURRENCY_CONTROL", "MISSING_IDEMPOTENCY", "MISSING_ASYNC_BOUNDARY", "MISSING_KEY_DISTRIBUTION", "MISSING_INVENTORY_CONSISTENCY"]', 1);
insert into failure_patterns values ('notification', 'Consumer Lag · 재시도 폭풍', '외부 발송 provider가 느려지자 컨슈머가 응답을 기다리느라 처리량이 떨어지고, 실패한 메시지의 즉시 재시도가 유입량을 부풀려 lag이 눈덩이처럼 쌓이는 장애.', '["컨슈머 그룹 lag이 계속 증가한다", "provider 호출이 타임아웃으로 끝난다", "같은 메시지의 재시도 로그가 반복된다"]', '["큐 적체(lag) 단조 증가", "외부 의존성 지연 ≥ 수백 ms", "컨슈머 처리량 하락", "재시도 비율 증가"]', '["consumer group notify-workers lag=… partition=…", "provider call timed out after 800ms channel=sms", "retrying message id=msg-… attempt=3"]', '["죽은 provider를 끝까지 기다리는 호출(타임아웃·차단기 없음)", "백오프 없는 즉시 재시도", "재처리에 대비한 멱등 처리 부재"]', '[{"fix": "컨슈머만 늘리기", "why": "provider가 느린 동안 컨슈머 하나당 처리량은 그대로라 늘린 만큼 provider 동시 호출만 늘어난다. 재시도가 유입을 부풀리는 한 lag은 줄지 않는다."}, {"fix": "재시도 횟수만 늘리기", "why": "실패한 메시지가 다시 큐로 들어와 유입량이 커진다 — 재시도 폭풍을 키우는 조치다."}]', '["Circuit Breaker로 죽은 provider를 빠르게 실패 처리", "Retry Backoff로 재시도 간격 벌리기", "증상이 잡힌 뒤 컨슈머 증설로 적체 소화"]', '["provider별 타임아웃·차단기·DLQ", "Idempotent Consumer로 재처리 안전성 확보", "lag 기반 알림"]', '["MISSING_CIRCUIT_BREAKER", "MISSING_RETRY_BACKOFF", "MISSING_DLQ", "MISSING_IDEMPOTENT_CONSUMER", "MISSING_ASYNC_BOUNDARY"]', 2);
insert into failure_patterns values ('product-browsing', 'Cache Stampede (Dogpile)', '인기 키의 캐시가 한꺼번에 만료되거나 정책이 맞지 않아 적중률이 떨어지고, 동시에 몰린 cache miss가 같은 쿼리를 DB에 중복으로 쏟아 읽기 계층이 무너지는 장애.', '["캐시 적중률이 급락한다", "같은 상품 키에 대한 miss가 동시에 몰린다", "DB 읽기 부하와 P95가 함께 오른다"]', '["캐시 적중률 < 70%", "DB 읽기 부하 ≥ 80%", "P95 지연 증가", "504 게이트웨이 타임아웃"]', '["cache miss key=product:{id} (hot)", "replica read queue depth high", "GET /products/{id} 504 gateway timeout"]', '["데이터 특성과 무관하게 같은 TTL을 쓰는 캐시 정책", "동시 miss를 하나로 합치지 않는 조회 경로", "읽기 용량을 늘릴 경로(replica) 부재"]', '[{"fix": "Read Replica만 추가하기", "why": "읽기 용량은 늘지만 원인(적중률 하락·중복 조회)은 그대로라 replica도 같은 중복 쿼리를 받는다. replica lag으로 최신성도 떨어진다."}]', '["Single-flight로 동시 miss를 하나의 DB 조회로 합치기", "캐시 정책 분리로 적중률 회복", "그 뒤 필요하면 Read Replica"]', '["키 성격별 TTL·지터", "인기 키 사전 워밍·분산", "적중률 기반 알림"]', '["MISSING_SINGLE_FLIGHT", "MISSING_CACHE_POLICY_SEPARATION", "MISSING_READ_REPLICA", "MISSING_KEY_DISTRIBUTION"]', 3);
insert into failure_patterns values ('payment', '외부 PG 지연 · 커넥션 고갈 전파', '외부 PG 응답이 느려지자 결제 처리가 커넥션을 오래 붙잡고, outbox가 쌓이면서 같은 풀을 쓰는 주문 처리까지 함께 막히는 장애. 응답 유실 뒤 재시도가 이중 결제를 만들 위험도 함께 커진다.', '["PG 승인 호출이 타임아웃으로 끝난다", "outbox 미처리 이벤트가 쌓인다", "결제와 무관한 주문 API까지 커넥션 대기로 느려진다"]', '["외부 의존성 지연 ≥ 500ms", "커넥션 풀 사용률 ≥ 95%", "outbox 적체 증가", "주문 API 에러율 상승"]', '["PG approve timed out after 1200ms orderId=ORD-…", "HikariPool-main - Connection is not available", "outbox pending events=…"]', '["결제와 주문이 커넥션 풀을 공유(격벽 없음)", "트랜잭션 안에서 외부 호출", "멱등성 키 없는 재시도"]', '[{"fix": "디스패처만 늘리기", "why": "outbox 처리량은 오르지만 PG 동시 호출이 늘어 PG 지연이 더 길어질 수 있고, 멱등성 키가 없으면 재시도가 중복 결제를 만든다."}]', '["결제 커넥션 풀 격리(bulkhead)로 주문 처리 보호", "멱등성 키를 붙인 재시도", "그 뒤 디스패처 증설로 적체 소화"]', '["외부 호출을 트랜잭션 밖으로", "PG 호출 타임아웃·백오프", "정산 대사로 중복 탐지"]', '["MISSING_PAYMENT_IDEMPOTENCY", "MISSING_TRANSACTION_BOUNDARY", "MISSING_PG_RETRY_BACKOFF", "MISSING_RETRY_BACKOFF", "MISSING_CIRCUIT_BREAKER", "MISSING_IDEMPOTENCY"]', 4);
insert into failure_patterns values ('reservation', '락 경합 · 홀드 누수', '좌석 예약이 넓은 범위의 락을 잡아 무관한 요청까지 줄을 서고, 결제하지 않고 떠난 사용자의 홀드가 오래 남아 실제 재고보다 적게 팔리는 장애.', '["예약 요청이 lock wait timeout으로 실패한다", "락 대기자 수가 늘어난다", "빈 좌석이 있는데도 ''매진''에 가까운 실패가 난다"]', '["DB 쓰기 부하 ≥ 80%", "락 대기 수 증가", "예약 에러율 상승", "홀드 만료 건수 증가"]', '["reservation failed: lock wait timeout seat=C-12", "lock contention: … waiters", "hold expired seat=… (no payment)"]', '["공연·구역 단위처럼 넓은 락", "결제 시간보다 훨씬 긴 홀드 타임아웃", "확인과 확정 사이의 경쟁(비원자적 재고 확인)"]', '[{"fix": "홀드 타임아웃만 크게 줄이기", "why": "점유는 빨리 풀리지만 정상 사용자의 결제 도중 홀드가 풀려 다른 사람에게 팔리는 문제가 생긴다. 락 경합 자체는 그대로다."}]', '["락을 좌석 단위로 세분화", "원자적 재고 확인으로 낭비성 재시도 제거", "홀드 타임아웃을 실제 결제 시간에 맞추기"]', '["예약·결제 상태 머신과 만료 처리", "재고 정합성 점검", "경합 지표 알림"]', '["MISSING_RESERVATION_LOCKING", "MISSING_RESERVATION_TIMEOUT", "MISSING_CONCURRENCY_CONTROL", "MISSING_INVENTORY_CONSISTENCY"]', 5);
insert into failure_patterns values ('batch-settlement', '배치 재시작 · 중복 정산', '정산 배치가 중간에 실패하면 처음부터 다시 돌고, 이미 반영된 레코드가 다시 처리되면서 중복 정산이 생기는 장애. 재처리 범위가 클수록 마감 시간도 밀린다.', '["배치가 실패 뒤 처음부터 재실행된다", "이미 반영된 가맹점 정산이 중복으로 잡힌다", "정산 API 호출이 느려지며 청크 실패가 반복된다"]', '["에러율(중복·실패 레코드) 증가", "재처리 대기 레코드 증가", "외부 정산 API 지연"]', '["duplicate settlement row merchant=… (already applied)", "chunk failed — reprocessing … records", "settlement API slow: 450ms"]', '["체크포인트 없는 배치", "레코드 단위 멱등성 없는 반영", "실패 범위를 키우는 큰 청크"]', '[{"fix": "청크 크기만 줄이기", "why": "실패 시 재처리 범위는 줄지만 커밋 오버헤드로 정상 처리량이 떨어진다. 재시작이 처음부터라면 근본 문제는 그대로이고, 중복 반영도 막지 못한다."}]', '["체크포인트 재개로 실패한 청크부터 다시", "멱등한 정산 재처리로 중복 반영 차단", "청크 크기는 그다음 미세 조정"]', '["대사(reconciliation) 배치", "재시작 가능한 Job 설계", "처리 이력 테이블"]', '["MISSING_RESTARTABILITY", "MISSING_CHUNKING", "MISSING_RECONCILIATION", "MISSING_IDEMPOTENT_CONSUMER"]', 6);
insert into failure_patterns values ('autoscaling', 'OOM Crash Loop · 롤아웃 중 용량 손실', '트래픽이 폭증한 순간 리소스 제한이 맞지 않는 Pod가 OOM으로 재시작을 반복하고, 겹친 롤링 배포가 남은 용량까지 깎아 ''늘려도 안 늘어나는'' 장애.', '["Pod가 OOMKilled(exit 137)로 재시작을 반복한다", "ingress가 healthy upstream이 없다고 503을 낸다", "Pod 수를 늘려도 가용 용량이 거의 그대로다"]', '["재시작 횟수 증가", "에러율(503) 급증", "P95 지연 증가", "가용 Pod 비율 하락"]', '["pod recommend-api-… OOMKilled (exit 137), restarting", "503 no healthy upstream for recommend-api", "request latency p95=…ms"]', '["메모리 request/limit이 실제 사용량과 맞지 않음", "readiness probe·PDB 없는 롤링 배포", "확장 지표(관측) 부재"]', '[{"fix": "Pod만 늘리기", "why": "새로 뜬 Pod도 같은 limit으로 OOM kill되거나 롤아웃에 휩쓸린다 — 두 패널티가 곱해져 수평 확장만으로는 거의 개선되지 않는다."}]', '["리소스 제한 조정으로 crash loop 해소", "무중단 배포 안전장치(readiness·PDB)", "그 뒤 Pod 증설"]', '["부하 테스트로 request/limit 산정", "HPA 지표·알림", "배포 시간대·안전장치 기본값"]', '["MISSING_RESOURCE_LIMITS", "MISSING_ROLLOUT_SAFETY", "MISSING_AUTOSCALING", "MISSING_OBSERVABILITY"]', 7);

alter table learning_concepts add column bad_fixes jsonb not null default '[]'::jsonb;
alter table learning_concepts add column when_not_to_use text not null default '';
update learning_concepts set bad_fixes = '["요청 처리 경로 안에서 모든 일을 동기로 끝내려 스레드·커넥션을 늘리기", "큐를 넣되 소비자 처리 실패·중복을 다루지 않기"]'::jsonb, when_not_to_use = '사용자가 결과를 즉시 받아야 하고 처리 시간이 짧은 작업(단건 조회, 짧은 검증)에는 큐가 지연과 운영 비용만 더한다.' where risk_key = 'MISSING_ASYNC_BOUNDARY';
update learning_concepts set bad_fixes = '["전체 데이터를 한 트랜잭션으로 처리해 실패 시 전부 롤백", "청크를 아주 작게 쪼개 커밋 오버헤드로 처리량을 잃기"]'::jsonb, when_not_to_use = '데이터가 작고 한 번에 원자적으로 반영돼야 하는 작업이라면 청크로 나누면 중간 상태가 노출된다.' where risk_key = 'MISSING_CHUNKING';
update learning_concepts set bad_fixes = '["실패하면 처음부터 다시 돌리기", "재시작 지점만 기록하고 이미 반영된 레코드의 중복은 신경 쓰지 않기"]'::jsonb, when_not_to_use = '몇 초 안에 끝나는 작은 배치는 체크포인트 저장·조회 비용이 재실행 비용보다 크다.' where risk_key = 'MISSING_RESTARTABILITY';
update learning_concepts set bad_fixes = '["모든 키에 같은 TTL을 쓰고 적중률이 떨어지면 TTL만 늘리기", "정책을 너무 잘게 나눠 아무도 설명할 수 없게 만들기"]'::jsonb, when_not_to_use = '데이터 종류가 하나뿐이거나 변경 빈도가 비슷하면 정책 분리는 복잡도만 늘린다.' where risk_key = 'MISSING_CACHE_POLICY_SEPARATION';
update learning_concepts set bad_fixes = '["Hot key 하나를 그대로 두고 캐시 노드만 늘리기", "키를 쪼개고 합산 정합성을 따로 다루지 않기"]'::jsonb, when_not_to_use = '트래픽이 키 전체에 고르게 퍼져 있다면 키 분산은 읽기·합산 비용만 늘린다.' where risk_key = 'MISSING_KEY_DISTRIBUTION';
update learning_concepts set bad_fixes = '["동시 miss를 그대로 DB에 보내고 DB 용량만 늘리기", "single-flight 대기 시간에 상한을 두지 않아 한 느린 조회가 모두를 묶기"]'::jsonb, when_not_to_use = '캐시 miss가 드물고 키가 분산돼 동시 miss가 거의 없다면 대기 조정 로직이 이득 없이 지연만 만든다.' where risk_key = 'MISSING_SINGLE_FLIGHT';
update learning_concepts set bad_fixes = '["원인(적중률 하락·중복 조회)을 그대로 두고 replica만 추가", "쓰기 직후 읽기를 replica로 보내 방금 쓴 값을 못 보게 하기"]'::jsonb, when_not_to_use = '쓰기가 병목이거나 ''방금 쓴 값''을 바로 읽어야 하는 경로에는 replica가 도움이 안 되거나 오히려 정합성 문제를 만든다.' where risk_key = 'MISSING_READ_REPLICA';
update learning_concepts set bad_fixes = '["홀드 타임아웃을 극단적으로 줄여 정상 결제 도중 홀드를 풀기", "만료를 정리하는 작업 없이 타임아웃 값만 두기"]'::jsonb, when_not_to_use = '재고가 넉넉해 경쟁이 없는 예약이라면 짧은 홀드는 사용자 경험만 해친다.' where risk_key = 'MISSING_RESERVATION_TIMEOUT';
update learning_concepts set bad_fixes = '["Pod 수만 늘리고 리소스 제한·배포 안전장치는 그대로 두기", "지표 없이 고정된 일정으로만 확장하기"]'::jsonb, when_not_to_use = '부하가 예측 가능하고 일정하다면 고정 용량이 더 단순하고 저렴하다. 콜드 스타트가 긴 서비스는 반응형 확장이 폭증을 따라가지 못한다.' where risk_key = 'MISSING_AUTOSCALING';
update learning_concepts set bad_fixes = '["limit을 너무 낮게 잡아 정상 부하에서도 스로틀링·OOM", "limit을 없애 한 Pod가 노드 전체 메모리를 먹게 두기"]'::jsonb, when_not_to_use = '측정 없이 감으로 정한 값은 안 정한 것보다 나쁠 수 있다 — 먼저 실제 사용량을 재야 한다.' where risk_key = 'MISSING_RESOURCE_LIMITS';
update learning_concepts set bad_fixes = '["재시도를 없애 중복을 피하기(대신 유실이 생김)", "멱등성 키를 저장만 하고 만료·충돌 처리를 하지 않기"]'::jsonb, when_not_to_use = '읽기 전용 요청이나 자연스럽게 멱등한 연산(값 덮어쓰기)에는 별도 키가 필요 없다.' where risk_key = 'MISSING_IDEMPOTENCY';
update learning_concepts set bad_fixes = '["애플리케이션 메모리 락으로 여러 인스턴스 간 경쟁을 막으려 하기", "넓은 범위의 락으로 경합을 해결하려다 처리량을 잃기"]'::jsonb, when_not_to_use = '경쟁이 거의 없는 데이터에 비관적 락을 걸면 비용만 든다 — 낙관적 검증이나 유니크 제약으로 충분할 수 있다.' where risk_key = 'MISSING_CONCURRENCY_CONTROL';
update learning_concepts set bad_fixes = '["중복이 나면 메시지를 버리지 않고 그냥 다시 처리하기", "처리 이력 테이블을 무한히 쌓기"]'::jsonb, when_not_to_use = '처리가 본래 멱등하거나(상태 덮어쓰기) 중복이 무해한 메시지라면 이력 저장은 비용만 든다.' where risk_key = 'MISSING_IDEMPOTENT_CONSUMER';
update learning_concepts set bad_fixes = '["응답이 없으면 같은 결제를 키 없이 다시 요청하기", "멱등성 키를 요청마다 새로 만들어 무용지물로 만들기"]'::jsonb, when_not_to_use = '결제 수단이 자체 멱등성을 보장하고 그 키를 그대로 쓸 수 있다면 중복 저장소를 따로 두지 않아도 된다.' where risk_key = 'MISSING_PAYMENT_IDEMPOTENCY';
update learning_concepts set bad_fixes = '["외부 PG 호출을 DB 트랜잭션 안에 두어 커넥션을 붙잡기", "트랜잭션을 너무 잘게 쪼개 중간 상태를 노출하기"]'::jsonb, when_not_to_use = '모든 작업이 같은 DB 안에서 짧게 끝난다면 경계를 나눌 이유가 없다.' where risk_key = 'MISSING_TRANSACTION_BOUNDARY';
update learning_concepts set bad_fixes = '["공연·구역 단위의 넓은 락으로 정합성만 지키기", "분산 락의 만료를 처리 시간보다 짧게 잡기"]'::jsonb, when_not_to_use = '좌석 지정이 없는 수량 판매라면 행 락보다 원자적 카운터가 단순하다.' where risk_key = 'MISSING_RESERVATION_LOCKING';
update learning_concepts set bad_fixes = '["확인과 확정을 따로 해 경쟁 구간을 남기기", "재고 불일치를 사후 수동 보정으로만 처리"]'::jsonb, when_not_to_use = '재고가 무한하거나 초과 판매가 허용되는(나중에 보상) 상품에는 강한 정합성이 비용 대비 이득이 없다.' where risk_key = 'MISSING_INVENTORY_CONSISTENCY';
update learning_concepts set bad_fixes = '["불일치를 발견해도 자동 보정 없이 알림만", "대사를 실시간 경로에 넣어 처리 지연을 만들기"]'::jsonb, when_not_to_use = '외부 시스템과 주고받는 값이 없거나 원장 하나가 유일한 진실이라면 대사할 대상이 없다.' where risk_key = 'MISSING_RECONCILIATION';
update learning_concepts set bad_fixes = '["지표를 모두 수집하되 알림 기준이 없어 아무도 보지 않기", "장애 중에 처음으로 대시보드를 만들기"]'::jsonb, when_not_to_use = '관측은 언제나 필요하다 — 다만 모든 것을 같은 무게로 수집하면 신호가 묻힌다. 핵심 지표(SLO)부터.' where risk_key = 'MISSING_OBSERVABILITY';
update learning_concepts set bad_fixes = '["임계값을 너무 낮게 잡아 정상 사용자까지 거절", "레이트 리밋만 두고 거절된 요청에 재시도 안내를 하지 않아 재시도 폭풍 유발"]'::jsonb, when_not_to_use = '내부 배치처럼 호출자가 하나이고 속도를 스스로 조절하는 경로에는 큐·백프레셔가 더 맞다.' where risk_key = 'MISSING_RATE_LIMIT';
update learning_concepts set bad_fixes = '["재시도 횟수만 늘리기(재시도 폭풍)", "지터 없는 고정 간격으로 모든 클라이언트가 동시에 재시도"]'::jsonb, when_not_to_use = '멱등하지 않은 작업에는 백오프 재시도가 중복을 만든다 — 멱등성부터 갖춘다.' where risk_key = 'MISSING_RETRY_BACKOFF';
update learning_concepts set bad_fixes = '["DLQ에 넣고 아무도 들여다보지 않기", "일시적 오류까지 즉시 DLQ로 보내 재처리 기회를 잃기"]'::jsonb, when_not_to_use = '모든 메시지를 반드시 순서대로 처리해야 하는 흐름에서는 한 메시지를 빼는 것이 순서를 깨뜨린다.' where risk_key = 'MISSING_DLQ';
update learning_concepts set bad_fixes = '["차단기 없이 타임아웃만 길게 늘리기", "차단기를 너무 민감하게 잡아 정상 순간 장애에도 OPEN"]'::jsonb, when_not_to_use = '대체 경로가 없고 반드시 성공해야 하는 호출이라면 빠른 실패가 사용자에게 더 나쁠 수 있다 — 큐로 미루는 편이 낫다.' where risk_key = 'MISSING_CIRCUIT_BREAKER';
update learning_concepts set bad_fixes = '["PG 타임아웃마다 즉시 재시도", "멱등성 키 없이 백오프만 적용"]'::jsonb, when_not_to_use = 'PG가 명시적으로 거절(카드 한도 초과 등)한 요청은 재시도해도 결과가 같다 — 재시도는 일시적 오류에만.' where risk_key = 'MISSING_PG_RETRY_BACKOFF';
update learning_concepts set bad_fixes = '["장애 중에 배포를 강행해 남은 용량까지 잃기", "readiness probe 없이 rolling update만 설정"]'::jsonb, when_not_to_use = '트래픽이 없는 내부 도구라면 PDB·점진 배포는 배포 시간만 늘린다.' where risk_key = 'MISSING_ROLLOUT_SAFETY';
