-- ADR-0048 (PLAN.md Round E24) — 공식 7개 시나리오를 미션 콘텐츠와 함께 v2로 한 번에 올린다.
-- v1은 그대로 둔다(진행 중·완료 세션과 v1 토론은 v1에 묶여 남는다). 새 세션은 최신 PUBLISHED인 v2를 고른다.
-- INITIAL 프롬프트는 요구사항 질의(M1)를 위해 일부러 줄였다 — 빠진 수치는 clarifications의 답(requirementKey로
-- 공개 개요에서도 숨김)에 있다. FOLLOWUP 변형은 v1 문구 그대로에 M7 breaks만 더했고, INCIDENT·버전 규칙은 v1에서 복사한다.

-- coupon
insert into scenario_versions (id, scenario_id, version_no, status, followup_rules, incident_rules) select 'a0000000-0000-0000-0000-000000000020', scenario_id, 2, 'PUBLISHED', followup_rules, incident_rules from scenario_versions where id = 'a0000000-0000-0000-0000-000000000003';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('a0000000-0000-0000-0000-000000000020', 1, 'INITIAL', null, '{"prompt": "선착순 쿠폰 발급 시스템을 설계하세요. 이벤트가 시작되는 순간 많은 사용자가 동시에 몰립니다.", "clarifications": [{"id": "users", "question": "이벤트 시작 직후 몇 명 정도가 몰리나요?", "answer": "약 100만 명이 이벤트 시작 직후 접속합니다.", "critical": true, "requirementKey": "targetUsers"}, {"id": "total", "question": "쿠폰은 몇 장인가요?", "answer": "1만 장입니다.", "critical": true, "requirementKey": "totalCoupons"}, {"id": "dup", "question": "한 사용자가 여러 장 받을 수 있나요?", "answer": "1인 1장입니다. 중복 발급은 절대 허용되지 않습니다.", "critical": true, "requirementKey": "duplicateIssueAllowed"}, {"id": "response", "question": "발급 결과를 나중에 알려줘도 되나요?", "answer": "아니요. 사용자는 요청 즉시 성공 또는 실패 응답을 받아야 합니다.", "critical": true, "requirementKey": "responseMode"}, {"id": "expiry", "question": "쿠폰 유효기간은 얼마인가요?", "answer": "발급 후 7일입니다. 설계에 큰 영향은 없습니다.", "critical": false}, {"id": "button", "question": "발급 버튼 디자인은 정해졌나요?", "answer": "디자인팀 소관입니다.", "critical": false}], "estimation": [{"key": "peakRps", "label": "피크 발급 요청", "unit": "req/s", "answer": 100000, "hint": "100만 명이 첫 10초 안에 한 번씩 누른다면?"}, {"key": "successWrites", "label": "성공 발급 확정 쓰기 총량", "unit": "건", "answer": 10000, "hint": "성공할 수 있는 요청은 몇 건인가?"}], "assumptions": [{"id": "traffic-estimate", "text": "트래픽은 예상치(약 100만 명)를 넘지 않는다"}, {"id": "one-device", "text": "사용자는 한 기기에서 한 번만 요청한다"}, {"id": "redis-available", "text": "Redis는 장애 없이 동작한다"}, {"id": "single-region", "text": "단일 리전에서 운영한다"}], "constraints": {"budgetPerMonth": 3000, "teamSize": 3, "opsExperience": {"cache": "HIGH", "db": "MEDIUM", "queue": "LOW"}}}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content)
select 'a0000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition,
       jsonb_build_object('variants', (select jsonb_agg(v || jsonb_build_object('breaks', coalesce('{"traffic-spike": ["traffic-estimate"], "duplicate-issue-spike": ["one-device"], "bot-traffic": ["traffic-estimate", "one-device"]}'::jsonb -> (v->>'key'), '[]'::jsonb)) order by ord)
                                       from jsonb_array_elements(content->'variants') with ordinality as t(v, ord)))
from scenario_steps where scenario_version_id = 'a0000000-0000-0000-0000-000000000003' and step_type = 'FOLLOWUP';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) select 'a0000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition, content from scenario_steps where scenario_version_id = 'a0000000-0000-0000-0000-000000000003' and step_type = 'INCIDENT';

-- notification
insert into scenario_versions (id, scenario_id, version_no, status, followup_rules, incident_rules) select 'c0000000-0000-0000-0000-000000000020', scenario_id, 2, 'PUBLISHED', followup_rules, incident_rules from scenario_versions where id = 'c0000000-0000-0000-0000-000000000003';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('c0000000-0000-0000-0000-000000000020', 1, 'INITIAL', null, '{"prompt": "주문·결제·배송 이벤트가 발생할 때마다 사용자에게 알림을 보내는 시스템을 설계하세요.", "clarifications": [{"id": "channels", "question": "어떤 채널로 보내나요?", "answer": "이메일·푸시·SMS 세 가지이며, 각각 외부 provider를 씁니다.", "critical": true}, {"id": "timing", "question": "알림이 이벤트와 동시에 가야 하나요?", "answer": "아니요. 비동기로 보내도 되지만 최종적으로는 반드시 전달돼야 합니다.", "critical": true, "requirementKey": "deliveryMode"}, {"id": "volume", "question": "이벤트는 초당 몇 건인가요?", "answer": "평시 초당 50건입니다.", "critical": true, "requirementKey": "eventsPerSecond"}, {"id": "dup", "question": "같은 알림이 두 번 가도 되나요?", "answer": "안 됩니다. 특히 결제 완료 알림의 중복은 바로 민원이 됩니다.", "critical": true, "requirementKey": "duplicateDeliveryAllowed"}, {"id": "template", "question": "알림 문구는 누가 관리하나요?", "answer": "마케팅팀이 관리합니다(설계 범위 밖).", "critical": false}], "estimation": [{"key": "dailyMessages", "label": "하루 발송 메시지 수(이벤트당 1건)", "unit": "건", "answer": 4320000, "hint": "초당 50건 × 하루"}, {"key": "concurrentCalls", "label": "provider 응답이 3초일 때 초당 50건을 처리하는 데 필요한 동시 호출 수", "unit": "개", "answer": 150, "hint": "동시에 처리 중인 수 = 처리율 × 처리 시간"}], "assumptions": [{"id": "provider-fast", "text": "외부 provider는 200ms 안에 응답한다"}, {"id": "steady", "text": "이벤트는 하루 내내 고르게 들어온다"}, {"id": "well-formed", "text": "이벤트 데이터 형식은 항상 올바르다"}, {"id": "no-order", "text": "알림 순서 보장은 필요 없다"}], "constraints": {"budgetPerMonth": 2000, "teamSize": 2, "opsExperience": {"queue": "MEDIUM", "cache": "LOW"}}}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content)
select 'c0000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition,
       jsonb_build_object('variants', (select jsonb_agg(v || jsonb_build_object('breaks', coalesce('{"volume-spike": ["steady"], "malformed-events": ["well-formed"], "provider-degradation": ["provider-fast"]}'::jsonb -> (v->>'key'), '[]'::jsonb)) order by ord)
                                       from jsonb_array_elements(content->'variants') with ordinality as t(v, ord)))
from scenario_steps where scenario_version_id = 'c0000000-0000-0000-0000-000000000003' and step_type = 'FOLLOWUP';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) select 'c0000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition, content from scenario_steps where scenario_version_id = 'c0000000-0000-0000-0000-000000000003' and step_type = 'INCIDENT';

-- product-browsing
insert into scenario_versions (id, scenario_id, version_no, status, followup_rules, incident_rules) select 'd0000000-0000-0000-0000-000000000020', scenario_id, 2, 'PUBLISHED', followup_rules, incident_rules from scenario_versions where id = 'd0000000-0000-0000-0000-000000000003';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('d0000000-0000-0000-0000-000000000020', 1, 'INITIAL', null, '{"prompt": "상품 상세 페이지에서 가격·재고·리뷰를 함께 보여주는 조회 시스템을 설계하세요.", "clarifications": [{"id": "traffic", "question": "평시 트래픽은 얼마인가요?", "answer": "초당 500건 정도입니다.", "critical": true, "requirementKey": "baselineRps"}, {"id": "price", "question": "가격이 잠깐이라도 이전 값이면 안 되나요?", "answer": "가격은 항상 최신이어야 합니다. 결제 금액과 달라지면 안 됩니다.", "critical": true, "requirementKey": "priceFreshnessRequired"}, {"id": "review", "question": "리뷰도 실시간이어야 하나요?", "answer": "리뷰는 몇 분 늦게 보여도 괜찮습니다.", "critical": true, "requirementKey": "reviewStaleAllowed"}, {"id": "writes", "question": "상품 정보는 얼마나 자주 바뀌나요?", "answer": "가격·재고는 하루 수십 번, 리뷰는 꾸준히 추가됩니다. 읽기가 압도적으로 많습니다.", "critical": false}, {"id": "images", "question": "상품 이미지는 어떻게 하나요?", "answer": "CDN이 이미 있습니다(설계 범위 밖).", "critical": false}], "estimation": [{"key": "peakRps", "label": "피크(평시의 20배) 조회 요청", "unit": "req/s", "answer": 10000}, {"key": "dbReads", "label": "캐시 적중률 90%일 때 피크에 DB로 가는 읽기", "unit": "req/s", "answer": 1000, "hint": "miss 비율 × 피크 요청"}], "assumptions": [{"id": "uniform", "text": "요청이 상품 전체에 고르게 퍼진다"}, {"id": "read-flat", "text": "읽기 트래픽은 크게 늘지 않는다"}, {"id": "same-ttl", "text": "가격·재고·리뷰를 같은 캐시 정책으로 다뤄도 된다"}, {"id": "single-db", "text": "DB 하나로 읽기를 감당할 수 있다"}], "constraints": {"budgetPerMonth": 2500, "teamSize": 3, "opsExperience": {"cache": "MEDIUM", "db": "HIGH", "cdn": "HIGH"}}}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content)
select 'd0000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition,
       jsonb_build_object('variants', (select jsonb_agg(v || jsonb_build_object('breaks', coalesce('{"traffic-spike": ["same-ttl", "single-db"], "flash-sale-hot-item": ["uniform"], "read-heavy-growth": ["read-flat", "single-db"]}'::jsonb -> (v->>'key'), '[]'::jsonb)) order by ord)
                                       from jsonb_array_elements(content->'variants') with ordinality as t(v, ord)))
from scenario_steps where scenario_version_id = 'd0000000-0000-0000-0000-000000000003' and step_type = 'FOLLOWUP';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) select 'd0000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition, content from scenario_steps where scenario_version_id = 'd0000000-0000-0000-0000-000000000003' and step_type = 'INCIDENT';

-- payment
insert into scenario_versions (id, scenario_id, version_no, status, followup_rules, incident_rules) select 'b1000000-0000-0000-0000-000000000020', scenario_id, 2, 'PUBLISHED', followup_rules, incident_rules from scenario_versions where id = 'b1000000-0000-0000-0000-000000000003';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('b1000000-0000-0000-0000-000000000020', 1, 'INITIAL', null, '{"prompt": "사용자가 상품을 주문하고 결제하는 시스템을 설계하세요. 외부 결제대행사(PG)와 연동합니다.", "clarifications": [{"id": "consistency", "question": "주문과 결제 상태가 잠깐 달라도 되나요?", "answer": "최종적으로 일치하면 되지만, 결제 금액은 반드시 정확해야 합니다.", "critical": true, "requirementKey": "consistencyMode"}, {"id": "dup", "question": "같은 결제가 두 번 될 수 있나요?", "answer": "절대 안 됩니다. 이중 결제는 환불·CS 비용으로 바로 이어집니다.", "critical": true, "requirementKey": "duplicateChargeAllowed"}, {"id": "rps", "question": "주문은 초당 몇 건인가요?", "answer": "평시 초당 30건입니다.", "critical": true, "requirementKey": "baselineOrderRps"}, {"id": "pg", "question": "PG 응답 시간은 어느 정도인가요?", "answer": "보통 300ms지만 가끔 수 초까지 늘어납니다.", "critical": true}, {"id": "refund", "question": "환불도 설계 범위인가요?", "answer": "이번 범위는 주문과 결제까지입니다.", "critical": false}], "estimation": [{"key": "concurrentPg", "label": "PG 응답 3초일 때 초당 30건을 처리하려면 동시에 열려 있어야 하는 PG 호출 수", "unit": "개", "answer": 90, "hint": "동시에 처리 중인 수 = 처리율 × 처리 시간"}, {"key": "dailyOrders", "label": "하루 주문 수", "unit": "건", "answer": 2592000}], "assumptions": [{"id": "pg-fast", "text": "PG는 항상 1초 안에 응답한다"}, {"id": "response-arrives", "text": "PG 응답은 반드시 클라이언트에 도착한다"}, {"id": "one-tx", "text": "주문 저장과 결제를 하나의 트랜잭션으로 묶을 수 있다"}, {"id": "shared-pool", "text": "주문과 결제가 같은 DB 커넥션 풀을 써도 된다"}], "constraints": {"budgetPerMonth": 3000, "teamSize": 4, "opsExperience": {"db": "HIGH", "queue": "MEDIUM"}}}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content)
select 'b1000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition,
       jsonb_build_object('variants', (select jsonb_agg(v || jsonb_build_object('breaks', coalesce('{"pg-latency-spike": ["pg-fast", "shared-pool"], "lost-response": ["response-arrives"], "no-shared-transaction": ["one-tx"]}'::jsonb -> (v->>'key'), '[]'::jsonb)) order by ord)
                                       from jsonb_array_elements(content->'variants') with ordinality as t(v, ord)))
from scenario_steps where scenario_version_id = 'b1000000-0000-0000-0000-000000000003' and step_type = 'FOLLOWUP';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) select 'b1000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition, content from scenario_steps where scenario_version_id = 'b1000000-0000-0000-0000-000000000003' and step_type = 'INCIDENT';

-- reservation
insert into scenario_versions (id, scenario_id, version_no, status, followup_rules, incident_rules) select 'b2000000-0000-0000-0000-000000000020', scenario_id, 2, 'PUBLISHED', followup_rules, incident_rules from scenario_versions where id = 'b2000000-0000-0000-0000-000000000003';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('b2000000-0000-0000-0000-000000000020', 1, 'INITIAL', null, '{"prompt": "인기 공연의 좌석 예약 시스템을 설계하세요.", "clarifications": [{"id": "dup", "question": "같은 좌석이 두 명에게 팔릴 수 있나요?", "answer": "절대 안 됩니다.", "critical": true, "requirementKey": "duplicateReservationAllowed"}, {"id": "consistency", "question": "예약 확정 여부를 나중에 알려줘도 되나요?", "answer": "좌석을 선택한 직후 확정 여부를 바로 보여줘야 합니다(강한 일관성).", "critical": true, "requirementKey": "consistencyMode"}, {"id": "rps", "question": "예약 시도는 초당 몇 건인가요?", "answer": "평시 초당 20건이고, 예약 오픈 직후에는 크게 늘어납니다.", "critical": true, "requirementKey": "baselineReservationRps"}, {"id": "hold", "question": "결제할 때까지 좌석을 잡아두나요?", "answer": "네. 좌석 선택부터 결제 완료까지 홀드합니다. 결제는 보통 3분 안에 끝납니다.", "critical": true}, {"id": "seats", "question": "공연당 좌석 수는?", "answer": "약 5,000석입니다.", "critical": false}], "estimation": [{"key": "openRps", "label": "예약 오픈 직후(평시의 15배) 예약 시도", "unit": "req/s", "answer": 300}, {"key": "heldSeats", "label": "평시 초당 20건이 모두 홀드에 성공하고 결제가 3분 걸릴 때 동시에 홀드된 좌석 수", "unit": "석", "answer": 3600, "hint": "동시에 처리 중인 수 = 처리율 × 처리 시간"}], "assumptions": [{"id": "everyone-pays", "text": "좌석을 고른 사용자는 대부분 결제를 끝낸다"}, {"id": "one-api", "text": "재고 확인과 예약 확정이 한 API 안에서 일어난다"}, {"id": "steady-load", "text": "예약 오픈 직후에도 시도량이 평시와 크게 다르지 않다"}, {"id": "coarse-lock-ok", "text": "공연 단위로 락을 잡아도 처리량이 충분하다"}], "constraints": {"budgetPerMonth": 2000, "teamSize": 2, "opsExperience": {"db": "HIGH", "cache": "MEDIUM"}}}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content)
select 'b2000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition,
       jsonb_build_object('variants', (select jsonb_agg(v || jsonb_build_object('breaks', coalesce('{"concurrent-surge": ["steady-load", "coarse-lock-ok"], "abandoned-holds": ["everyone-pays"], "split-check-and-reserve": ["one-api"]}'::jsonb -> (v->>'key'), '[]'::jsonb)) order by ord)
                                       from jsonb_array_elements(content->'variants') with ordinality as t(v, ord)))
from scenario_steps where scenario_version_id = 'b2000000-0000-0000-0000-000000000003' and step_type = 'FOLLOWUP';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) select 'b2000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition, content from scenario_steps where scenario_version_id = 'b2000000-0000-0000-0000-000000000003' and step_type = 'INCIDENT';

-- batch-settlement
insert into scenario_versions (id, scenario_id, version_no, status, followup_rules, incident_rules) select 'b3000000-0000-0000-0000-000000000020', scenario_id, 2, 'PUBLISHED', followup_rules, incident_rules from scenario_versions where id = 'b3000000-0000-0000-0000-000000000003';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('b3000000-0000-0000-0000-000000000020', 1, 'INITIAL', null, '{"prompt": "매일 새벽 거래 내역을 정산하는 배치 시스템을 설계하세요.", "clarifications": [{"id": "volume", "question": "하루 정산 대상은 몇 건인가요?", "answer": "약 100만 건입니다.", "critical": true, "requirementKey": "totalRecords"}, {"id": "failure", "question": "정산 도중 실패하면 어떻게 하나요?", "answer": "중간에 실패할 수 있고, 다시 처리해도 결과가 한 번만 반영돼야 합니다.", "critical": true, "requirementKey": "consistencyMode"}, {"id": "dup", "question": "같은 레코드가 두 번 반영되면 안 되나요?", "answer": "절대 안 됩니다. 가맹점에 금액이 두 번 지급됩니다.", "critical": true, "requirementKey": "duplicateSettlementAllowed"}, {"id": "window", "question": "언제까지 끝나야 하나요?", "answer": "새벽 2시에 시작해 오전 6시 전에 끝나야 합니다.", "critical": true}, {"id": "api", "question": "외부 시스템을 호출하나요?", "answer": "레코드마다 가맹점 정산 API를 호출합니다. 평소 50ms가 걸립니다.", "critical": false}], "estimation": [{"key": "throughput", "label": "4시간 안에 100만 건을 끝내려면 필요한 처리량", "unit": "건/s", "answer": 70}, {"key": "sequentialMinutes", "label": "API(50ms)를 하나씩 순서대로 호출하면 걸리는 시간", "unit": "분", "answer": 833, "hint": "100만 × 50ms"}], "assumptions": [{"id": "no-crash", "text": "배치 서버는 실행 도중 재시작되지 않는다"}, {"id": "api-fast", "text": "정산 API는 항상 50ms 안에 응답한다"}, {"id": "run-once", "text": "각 레코드는 한 번만 처리된다"}, {"id": "fixed-volume", "text": "정산 대상 건수는 매일 비슷하다"}], "constraints": {"budgetPerMonth": 1500, "teamSize": 2, "opsExperience": {"db": "HIGH", "queue": "LOW"}}}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content)
select 'b3000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition,
       jsonb_build_object('variants', (select jsonb_agg(v || jsonb_build_object('breaks', coalesce('{"confirmed-scale": ["fixed-volume"], "mid-run-failure": ["no-crash"], "reprocess-duplicate-risk": ["run-once"]}'::jsonb -> (v->>'key'), '[]'::jsonb)) order by ord)
                                       from jsonb_array_elements(content->'variants') with ordinality as t(v, ord)))
from scenario_steps where scenario_version_id = 'b3000000-0000-0000-0000-000000000003' and step_type = 'FOLLOWUP';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) select 'b3000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition, content from scenario_steps where scenario_version_id = 'b3000000-0000-0000-0000-000000000003' and step_type = 'INCIDENT';

-- autoscaling
insert into scenario_versions (id, scenario_id, version_no, status, followup_rules, incident_rules) select 'b4000000-0000-0000-0000-000000000020', scenario_id, 2, 'PUBLISHED', followup_rules, incident_rules from scenario_versions where id = 'b4000000-0000-0000-0000-000000000003';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('b4000000-0000-0000-0000-000000000020', 1, 'INITIAL', null, '{"prompt": "메인 화면에 노출되는 실시간 추천 API를 설계하세요. Kubernetes 위에서 운영합니다.", "clarifications": [{"id": "variance", "question": "트래픽 변동은 어느 정도인가요?", "answer": "시간대별로 크게 달라지고, 프로모션 때는 평시의 10배까지 튑니다.", "critical": true, "requirementKey": "trafficVariance"}, {"id": "deploy", "question": "배포는 어떻게 하나요?", "answer": "하루에도 여러 번 무중단 롤링 배포를 합니다.", "critical": true, "requirementKey": "deploymentModel"}, {"id": "baseline", "question": "평시 요청량과 Pod 처리량은?", "answer": "평시 초당 100건이고, Pod 하나가 초당 50건 정도를 처리합니다.", "critical": true}, {"id": "memory", "question": "Pod 메모리 사용량은?", "answer": "평시 300MB, 추천 모델 캐시를 올리면 700MB까지 늘어납니다.", "critical": true}, {"id": "model", "question": "추천 모델 학습도 설계하나요?", "answer": "범위 밖입니다. 학습된 모델을 받아서 씁니다.", "critical": false}], "estimation": [{"key": "peakPods", "label": "프로모션 피크(평시의 10배)에 필요한 Pod 수", "unit": "개", "answer": 20}, {"key": "peakMemoryGb", "label": "피크 Pod를 모두 띄울 때 필요한 메모리(모델 캐시 포함)", "unit": "GB", "answer": 14, "hint": "Pod 수 × Pod당 최대 메모리"}], "assumptions": [{"id": "stable-pods", "text": "Pod는 한번 뜨면 재시작 없이 안정적이다"}, {"id": "deploy-quiet", "text": "배포는 트래픽이 적을 때만 한다"}, {"id": "scale-enough", "text": "Pod만 늘리면 처리량이 늘어난다"}, {"id": "predictable-peak", "text": "트래픽 피크는 미리 예측할 수 있다"}], "constraints": {"budgetPerMonth": 2500, "teamSize": 3, "opsExperience": {"service": "MEDIUM", "gateway": "HIGH"}}}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content)
select 'b4000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition,
       jsonb_build_object('variants', (select jsonb_agg(v || jsonb_build_object('breaks', coalesce('{"confirmed-scale": ["predictable-peak", "scale-enough"], "resource-limit-incident": ["stable-pods"], "rollout-safety-incident": ["deploy-quiet"]}'::jsonb -> (v->>'key'), '[]'::jsonb)) order by ord)
                                       from jsonb_array_elements(content->'variants') with ordinality as t(v, ord)))
from scenario_steps where scenario_version_id = 'b4000000-0000-0000-0000-000000000003' and step_type = 'FOLLOWUP';
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) select 'b4000000-0000-0000-0000-000000000020', step_order, step_type, trigger_condition, content from scenario_steps where scenario_version_id = 'b4000000-0000-0000-0000-000000000003' and step_type = 'INCIDENT';
