-- docs/DRILLS_EXPANSION_PLAN.md M9 (PLAN.md Round E30, ADR-0049) — 8번째 공식 도메인 deployment.
-- 다른 도메인과 달리 처음부터 미션 콘텐츠를 담은 v1으로 시작한다(ADR-0048이 해결한 v1→v2 문제가 없음).
-- 인증 대상 도메인에는 들어가지 않는다(ADR-0049) — CertificationService.CERTIFICATION_DOMAINS.
insert into content_items (id, type, title, difficulty) values ('b5000000-0000-0000-0000-000000000001', 'SCENARIO', '카나리 배포', 'HARD');
insert into scenarios (id, content_id, domain, base_requirements) values ('b5000000-0000-0000-0000-000000000002', 'b5000000-0000-0000-0000-000000000001', 'deployment', '{"functional": ["주문 결제 API 운영", "새 버전 배포"], "nonFunctional": {"baselineRps": 800, "errorBudget": "에러율 1% 초과 시 장애", "deployFrequency": "하루 1회 이상"}}'::jsonb);
insert into scenario_versions (id, scenario_id, version_no, status) values ('b5000000-0000-0000-0000-000000000003', 'b5000000-0000-0000-0000-000000000002', 1, 'PUBLISHED');
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('b5000000-0000-0000-0000-000000000003', 1, 'INITIAL', null, '{"prompt": "주문 결제(checkout) 서비스의 새 버전 배포 방식을 설계하세요. 이 서비스는 매일 배포됩니다.", "clarifications": [{"id": "traffic", "question": "checkout 트래픽은 어느 정도인가요?", "answer": "평시 초당 800건입니다.", "critical": true, "requirementKey": "baselineRps"}, {"id": "errors", "question": "배포 중 에러는 어디까지 허용되나요?", "answer": "에러율이 1%를 넘으면 장애로 봅니다. 결제 실패는 바로 매출 손실입니다.", "critical": true, "requirementKey": "errorBudget"}, {"id": "frequency", "question": "배포는 얼마나 자주 하나요?", "answer": "하루 한 번 이상, 여러 팀이 같은 서비스를 배포합니다.", "critical": true, "requirementKey": "deployFrequency"}, {"id": "rollback", "question": "이전 버전으로 되돌리는 데 얼마나 걸리나요?", "answer": "이미지 교체는 1분 안에 끝나지만, DB 마이그레이션이 섞이면 되돌릴 수 없는 경우가 있습니다.", "critical": true}, {"id": "region", "question": "리전이 여러 개인가요?", "answer": "단일 리전입니다(설계에 큰 영향은 없습니다).", "critical": false}], "estimation": [{"key": "failedPerMinute", "label": "결함 버전이 트래픽 10%를 받으며 요청의 60%를 실패시킬 때 분당 실패 결제 수", "unit": "건/분", "answer": 2880, "hint": "초당 800 × 10% × 60% × 60초"}, {"key": "blastAtFull", "label": "같은 결함이 100%로 번졌을 때 분당 실패 결제 수", "unit": "건/분", "answer": 28800}], "assumptions": [{"id": "tests-catch", "text": "스테이징 테스트를 통과한 버전은 운영에서도 안전하다"}, {"id": "fast-rollback", "text": "문제가 생기면 언제든 바로 되돌릴 수 있다"}, {"id": "one-change", "text": "한 번의 배포에는 한 가지 변경만 들어간다"}, {"id": "errors-visible", "text": "새 버전의 에러는 전체 에러율에서 바로 보인다"}], "constraints": {"budgetPerMonth": 2000, "teamSize": 3, "opsExperience": {"gateway": "MEDIUM", "service": "HIGH"}}}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('b5000000-0000-0000-0000-000000000003', 2, 'FOLLOWUP', '{"afterStepOrder": 1}'::jsonb, '{"variants": [{"key": "many-teams", "prompt": "다섯 팀이 같은 날 checkout에 배포하게 되었습니다. 어떤 변경이 문제를 일으켰는지 어떻게 알아내고, 한 팀의 결함이 다른 팀 배포까지 막지 않게 하려면 설계를 어떻게 바꿔야 하는지 다시 검토하세요.", "targetRiskKey": null, "breaks": ["one-change"]}, {"key": "canary-blind", "prompt": "새 버전이 트래픽 5%만 받는 동안에는 전체 에러율이 거의 변하지 않아 아무도 결함을 눈치채지 못했습니다. 카나리 단계에서 결함을 어떻게 판단해 멈출지 설계를 다시 검토하세요.", "targetRiskKey": "MISSING_CANARY_ANALYSIS", "breaks": ["errors-visible", "tests-catch"]}, {"key": "irreversible-migration", "prompt": "이번 배포에 컬럼을 삭제하는 DB 마이그레이션이 포함되어, 이미지만 되돌려서는 이전 버전이 동작하지 않습니다. 되돌릴 수 있는 배포가 되도록 설계를 다시 검토하세요.", "targetRiskKey": "MISSING_ROLLBACK_PLAN", "breaks": ["fast-rollback"]}]}'::jsonb);
insert into scenario_steps (scenario_version_id, step_order, step_type, trigger_condition, content) values ('b5000000-0000-0000-0000-000000000003', 3, 'INCIDENT', '{"afterStepOrder": 2}'::jsonb, '{"prompt": "checkout 2.14.0 카나리 배포가 시작된 뒤 결제 실패가 늘고 있습니다. 카나리는 시간이 지나면 자동으로 트래픽 비율을 늘립니다. 대응하세요.", "changeReview": {"changes": [{"id": "retry", "text": "PG 호출 재시도 1회 → 3회"}, {"id": "price-rounding", "text": "할인 금액 반올림 로직을 공통 PriceCalculator로 교체"}, {"id": "ttl", "text": "장바구니 Redis TTL 300초 → 60초"}, {"id": "log-level", "text": "결제 로그 레벨 INFO → DEBUG"}], "culpritId": "price-rounding", "explanation": "공통 PriceCalculator가 쿠폰 없는 주문에서 null을 반환해 NullPointerException이 났습니다. 로그의 PriceCalculator.apply 스택이 단서였습니다."}}'::jsonb);

insert into learning_concepts (risk_key, category, label, summary, why_it_matters, symptoms, patterns, tradeoffs, related_domains, related_actions, related_challenges, display_order, related_concepts, bad_fixes, when_not_to_use)
values ('MISSING_CANARY_ANALYSIS', 'RESILIENCE', '카나리 분석·자동 중단', '새 버전을 일부 트래픽에만 먼저 내보내고, 그 구간의 지표로 계속 퍼뜨릴지 멈출지를 판단한다.', '결함은 테스트가 아니라 실제 트래픽에서 드러나는 경우가 많다. 카나리 구간을 따로 보지 않으면 5% 트래픽의 결함은 전체 에러율에 묻혀 안 보이다가, 100%가 된 뒤에야 장애가 된다.', '["배포 직후 전체 에러율이 아주 조금씩 오르다가 카나리 비율이 커질 때마다 계단처럼 뛴다", "에러 로그에 새 버전 태그(version=…-canary)만 찍힌다", "이전 버전 Pod에서는 같은 요청이 성공한다"]'::jsonb, '["버전별(카나리 vs 기준) 지표를 나눠 비교", "에러율·지연 임계를 넘으면 자동 중단·롤백", "단계적 확대(5% → 25% → 50% → 100%)와 단계 사이 관찰 시간"]'::jsonb, '배포가 느려지고(단계마다 관찰 시간), 카나리 트래픽이 적으면 통계적으로 판단하기 어렵다. 임계를 너무 낮게 잡으면 정상 변동에도 배포가 멈춘다.', '["deployment"]'::jsonb, '["PAUSE_ROLLOUT", "ROLLBACK"]'::jsonb, '[]'::jsonb, 60, '[{"key": "MISSING_OBSERVABILITY", "relation": "PREREQUISITE"}, {"key": "MISSING_ROLLOUT_SAFETY", "relation": "RELATED"}]'::jsonb, '["카나리 비율만 정하고 무엇을 보고 판단할지는 정하지 않기", "전체 에러율만 보고 카나리 구간을 따로 보지 않기"]'::jsonb, '트래픽이 매우 적어 카나리 구간에서 의미 있는 신호가 나오지 않는 서비스, 또는 스키마 변경처럼 일부만 새 버전으로 돌릴 수 없는 변경에는 다른 방법(다크 런치, 플래그)이 맞다.');
insert into learning_concepts (risk_key, category, label, summary, why_it_matters, symptoms, patterns, tradeoffs, related_domains, related_actions, related_challenges, display_order, related_concepts, bad_fixes, when_not_to_use)
values ('MISSING_ROLLBACK_PLAN', 'RESILIENCE', '롤백 계획', '문제가 생겼을 때 무엇을 기준으로, 얼마나 빨리, 어떤 순서로 이전 상태로 되돌리는지를 배포 전에 정한다.', '장애 중에 롤백 여부를 토론하면 그 시간만큼 실패가 쌓인다. 되돌릴 수 없는 변경(파괴적 마이그레이션)이 섞이면 롤백 버튼이 있어도 소용없다.', '["장애 중 ''롤백해도 되나?''를 논의하느라 첫 조치가 늦어진다", "이미지를 되돌렸는데 이전 버전이 새 스키마에서 실패한다", "롤백 뒤에도 일부 데이터가 새 형식으로 남아 있다"]'::jsonb, '["롤백 기준(에러율·지연 임계)과 결정권자를 배포 전에 명시", "확장-축소(expand/contract) 마이그레이션으로 되돌릴 수 있는 스키마 변경", "피처 플래그로 코드 배포와 기능 활성화를 분리", "Blue-Green으로 이전 환경을 남겨 두기"]'::jsonb, '되돌릴 수 있게 만드는 비용(두 단계 마이그레이션, 플래그 관리, 이중 환경)이 든다. 모든 변경을 되돌릴 수 있게 만들 수는 없으므로 무엇을 감수할지 정해야 한다.', '["deployment"]'::jsonb, '["ROLLBACK"]'::jsonb, '[]'::jsonb, 61, '[{"key": "MISSING_CANARY_ANALYSIS", "relation": "PREREQUISITE"}]'::jsonb, '["롤백 대신 ''빨리 고쳐서 다시 배포''(roll-forward)부터 시도하기", "이미지만 되돌리고 스키마·캐시·플래그 상태는 확인하지 않기"]'::jsonb, '되돌리는 것 자체가 위험한 변경(이미 외부로 나간 데이터 형식, 결제 상태 전이)은 롤백보다 roll-forward와 보상 처리가 안전할 수 있다.');
insert into failure_patterns values ('deployment', '결함 있는 배포 · 카나리 확산', '새 버전의 결함이 카나리 단계에서 드러나지 않거나 무시된 채 트래픽 비율이 커지며 실패가 계단처럼 늘어나는 장애. 원인은 인프라가 아니라 방금 나간 변경이다.', '["배포 시작 시각과 에러 증가 시작이 겹친다", "에러가 카나리 비율이 바뀔 때마다 계단처럼 오른다", "실패 요청이 새 버전에서만 난다"]', '["에러율 계단형 증가", "P95 지연 증가(클라이언트 재시도)", "트래픽·DB·캐시는 평소와 같음"]', '["NullPointerException at PriceCalculator.apply (version=2.14.0-canary)", "client retry #2 after 500 from version=2.14.0-canary", "rollout checkout-api 2.14.0: canary serving 40% of traffic"]', '["카나리 구간 지표를 따로 보지 않음", "자동 중단·롤백 임계 없음", "여러 변경이 한 배포에 섞여 원인 파악이 늦음"]', '[{"fix": "배포를 계속 진행해 빨리 끝내기", "why": "결함이 있는 버전의 비율이 커질수록 실패도 비례해서 커진다 — 카나리를 100%로 밀면 장애가 최대가 된다."}, {"fix": "서버·DB 용량부터 늘리기", "why": "트래픽·DB·캐시는 정상이다. 원인은 코드 결함이라 용량을 늘려도 실패율은 그대로다."}]', '["배포 일시 중지로 확산부터 멈추기", "롤백으로 결함 버전 트래픽을 0으로", "원인 변경을 찾은 뒤 수정 버전을 다시 카나리로"]', '["버전별 지표 비교와 자동 중단 임계", "되돌릴 수 있는 마이그레이션·피처 플래그", "한 배포에 한 가지 변경"]', '["MISSING_CANARY_ANALYSIS", "MISSING_ROLLBACK_PLAN", "MISSING_OBSERVABILITY", "MISSING_ROLLOUT_SAFETY"]', 8);
